export const LoadingState = Symbol('loading')
export const ErrorState = Symbol('error')
export const IdleState = Symbol('idle')
export const GithubThrottledState = Symbol('githubThrottled')
export const PossiblyOfflineState = Symbol('possiblyOffline')
